# nixpacks.toml
providers = ["node"]

[phases.setup]
# install Chromium so screenshots/Puppeteer can work if needed
nixPkgs = ["chromium"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[phases.start]
cmd = "npm start"